#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config"
RASI="$DIR/rofi/screenshot.rasi"
iDIR="$DIR/mako/icons"

# Theme Elements
prompt='Screenshot'
mesg="Directory :: $(xdg-user-dir PICTURES)"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	option_1=" Capture Desktop"
	option_2=" Capture Area"
	option_3=" Capture Window"
	option_4=" Capture in 5s"
	option_5=" Capture in 10s"
else
	option_1=""
	option_2=""
	option_3=""
	option_4="5s"
	option_5="10"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme "${RASI}"
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# notify and view screenshot
notify_view() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR"/picture.png "Screenshot Saved..."
	paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
}

# countdown
countdown() {
	for sec in $(seq "$1" -1 1); do
		notify-send -h string:x-canonical-private-synchronous:sys-notify-count -t 1000 -i "$iDIR"/timer.png "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow() {
	grimshot save output
	notify_view
}

shot5() {
	countdown '5'
	grimshot save output
	notify_view
}

shot10() {
	countdown '10'
	grimshot save output
	notify_view
}

shotwin() {
	grimshot save window
	notify_view
}

shotarea() {
grimshot save area
	notify_view
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		shotnow
	elif [[ "$1" == '--opt2' ]]; then
		shotarea
	elif [[ "$1" == '--opt3' ]]; then
		shotwin
	elif [[ "$1" == '--opt4' ]]; then
		shot5
	elif [[ "$1" == '--opt5' ]]; then
		shot10
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
"$option_1")
	run_cmd --opt1
	;;
"$option_2")
	run_cmd --opt2
	;;
"$option_3")
	run_cmd --opt3
	;;
"$option_4")
	run_cmd --opt4
	;;
"$option_5")
	run_cmd --opt5
	;;
esac
